name: release

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: Set up JDK 13
        uses: actions/setup-java@v2
        with:
          java-version: 13
          distribution: 'adopt'

      - name: Get current time
        uses: srfrnk/current-time@master
        id: current-time
        with:
          format: YYYYMMDDHHmmss

      - name: Get short sha
        id: short-sha
        run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"

      - name: Build with Gradle
        env:
          DATETIME: "${{ steps.current-time.outputs.formattedTime }}"
          SHORT_SHA: "${{ steps.short-sha.outputs.sha_short }}"
        run: >
          ./gradlew jib -x test
          -Djib.to.auth.username=${{ secrets.DOCKER_USERNAME }}
          -Djib.to.auth.password=${{ secrets.DOCKER_PASSWORD }}
          -Djib.to.tags=latest,$DATETIME$SHORT_SHA
